# Copyright (c) 2020 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#                https://developer.cisco.com/docs/licenses
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

rtr_grpc_port: 54700
rtr_destination_name: DEMODOCKER
source_interface: MgmtEth0/RP0/CPU0/0
sensor_groups:
  - sensor_name: LOAD
    sensor_paths: 
      - Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization
      - Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary
  - sensor_name: BGP
    sensor_paths:
      - Cisco-IOS-XR-ipv4-bgp-oper:bgp/config-instances/config-instance/config-instance-default-vrf
subscriptions:
  - name: SUBDOCKER
    sensor_groups:
      - name: LOAD
        sample_interval: 10
      - name: BGP
        sample_interval: 10
    destination_group: DEMODOCKER
ansible_network_os: iosxr