# Copyright (c) 2020 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#                https://developer.cisco.com/docs/licenses
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

--- 
  - name: Configurar el router IOS-XE
    hosts: csr
    gather_facts: False
    connection: network_cli
    vars_files:
      - vars/controller_vars.yml
      - vars/router_iosxe_vars.yml
    tasks:
      - name: Configurar sensor de telemetria y guardar configuracion
        ios_config:
          backup: yes
          backup_options:
            filename: backup.cfg
          lines: 
            - encoding encode-kvgpb
            - filter xpath {{ruta}}
            - stream yang-push
            - update-policy periodic {{periodicidad}}
            - receiver ip address {{direccion_controlador}} {{puerto_controlador}} protocol grpc-tcp
          parents:
            - telemetry ietf subscription {{nombre_suscripcion}}
      - name: Salvar configuracion a startup
        ios_config:
          save_when: modified
