# Copyright (c) 2020 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#                https://developer.cisco.com/docs/licenses
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
---
  - name: Configurar imagen TIG STACK 
    hosts: controller
    gather_facts: False
    tasks:
      - name: Instalar modulo Docker para Python
        pip:
          name: docker
      - name: Obtener imagen de docker
        docker_image:
          name: sarifern/tig-stack-tls
          tag: no-tls
          source: pull
      - name: Correr contenedor de docker 
        docker_container:
          name: docker-tig-no-tls
          image: sarifern/tig-stack-tls:no-tls
          state: started
          ulimits: nofile:66000:66000
          ports:
            - "3003:3003" #grafana
            - "54700:54700"       # grpc
            - "8086:8086"       #influx
            - "3004:8888"       # influxdb-admin
          
          